language: node_js
node_js:
- '8'
dist: trusty
sudo: false
addons:
  chrome: stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_success:
- bash travis/commit.sh
deploy:
  provider: npm
  email: nooooru@gmail.com
  api_key:
    secure: LG4gmAQohKm0VmxzPppCg1MbL9AnmJgEQUNXoSTZmyG96HoyWAk4KxSfkaa/PDDKHNleOxJPBkR0OD1raCPc0tuNC30hfUqMVX+X6VIQ2zs1m9Udi+Xfxi9Wm9FHTR8rFwAj2c9znXihWkjeGyId6cwFqglrlbbnZme6Yrdv51W94VEvf1aRQekXOG+8VoOHf5mo0iUxfb4LnE6mTxDtTDw7bYcW1PEx8ysHHT7sxDq6XBNU2UTNYvQo0C+Mb3LjBry5/du8yt8RINa+8c1MjIYjYxFlLfbnPe7K0HdRWh5Wd+pBBCkq2J8KE0iaQ0cTHkmqT2x6NxHXLml93YmZIe/8UaK3db7AC3YODim1us+bI3Qo4BxT7LyPTMZJVVT7JAgIwQ3enOJGWkz7z+FowNRsz2umOCik/O+KClfnG/J8Xttaa1KVlFP4JHMwEveR7lv6Jpa6/pDZYtTB+CET6UMeAB7UAkFpKeXqXzZW5sHoHFMUCyS1GEv5I5jff5nHfCw3DbCvoDjsO1yAzvXN3tC9TM2eeHqKRuG0JoCRdxSb5dComAmL7AlDRWTZK3MYvvBs1bJ/JbQWzEVJMvpCnXvO9w095USuzGGoblzb6xMWmYJsiS7SDvkUkcWXl4H2QCz4HUnFc0jtVHCaXYToZO/dAIK2uv/BgwQeFVPy6nM=
  on:
    repo: noru/vue-resource-mock
env:
  global:
    secure: uPzMR8FFvwoO9NNBACshbopAaNTAYRBocmIQzNHLuaSTInpJl4NUtQLO3SjEgW64dyE/gVk6+bJYRaDxlFo81gLDJJUIhtuoEUxP5AEbhJZGM91BYm3HZaOPq7gCrOiY0qSVj6TOEIJzpB1hGGCyPq62wy7q5J9Hp+tEyl0iXwva538CUaeB8z+090d3mKdJVFMt1ETph5fgvUMJQVf9uioaVC57f2Em/Yhh1ZxcQS9BLCM3T4DTXmlBg5gbNShjwDjOidLxPMTz7Gx5KprS5wYOxsGqdgVtA2miY/jezNPOg/A17b0fEqdWeIvDzmKCwi9mngNa2McYRR41HGZQi63fkFOjG70gga7a/JUhZNMEkS53k8ifUU5snODULW4cqsYut/vSqhRtaE/wREScOXIe2PfEd5TR5BGrlh1U1SMz4fty9z6lQ3iOuNqiMMQ556lnCmU6u4NVI4Z2saZ3/pNa1jqIzmiGvSuv2X4hAbh4HuPp4QcRkexnoqJqoBrwE9GUsc8uhShwV5dii2v+LVW/jKCiDdkJynfyeIf2ernsoQEW8rbQffgLPgVIhcM/TH+5P5Ef+TrT97G2P1m1zw4/U1cURiWZtyDQqkeVmn79YaAiXX7PWr0F/hhp4xwh0HPAlzcA1lVdGp6zK/ezlh0hipkvMG4sOUfEwfBESZQ=
